First week

## Matrix Computations

- Matrix and tensor products
- Matrics decomposition

In [2]:
import numpy as np

markov chains

In [8]:
A = np.matrix([[0.9,0.07,.02,.01],[0,.93,.05,0.02],
               [0,0,.85,.15],[0,0,0,1]])
print(A)

[[0.9  0.07 0.02 0.01]
 [0.   0.93 0.05 0.02]
 [0.   0.   0.85 0.15]
 [0.   0.   0.   1.  ]]


In [9]:
type(A)

numpy.matrixlib.defmatrix.matrix

In [24]:
currentState = np.matrix([[.85, .1,.05,0]])

In [18]:
print(currentState)

[[0.85 0.1  0.05 0.  ]]


In [19]:
afterOneYear = currentState @ A
print(afterOneYear)

[[0.765  0.1525 0.0645 0.018 ]]


In [22]:
#equivalent to
#first element in the output vector is a linear combination of states where we are 
#and vector of how to get into state 1 from different states
afterOneYear = A.T @ currentState.T
print(afterOneYear)

[[0.765 ]
 [0.1525]
 [0.0645]
 [0.018 ]]


matrix matrix product

In [26]:
Demand = np.array([[6,5,3,1],[3,6,2,2],[3,4,3,1]])
Prices = np.array([[1.5,1],[2,2.5],[5,4.5],[16,17]])

In [27]:
Pay = Demand @ Prices
print(Pay)

[[50.  49. ]
 [58.5 61. ]
 [43.5 43.5]]
